insert into TB_USER(email) values ('maria@gmail.com');
insert into TB_USER(email) values ('joao@gmail.com');
insert into TB_USER(email) values ('ana@gmail.com');
insert into TB_USER(email) values ('lucia@gmail.com');
insert into TB_USER(email) values ('joaquim@gmail.com');

insert into TB_MOVIE(title, description, score, count, image) values ('The Witcher', 'Geralt of Rivia, a solitary monster hunter, struggles to find his place in a world where people often prove more wicked than beasts.', 4.5, 2, 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/e5iqR3k7azXGK1tGaOLMnKycGku.jpg');
insert into TB_MOVIE(title, description, score, count, image) values ('Venom: Tempo de Carnificina', 'Em busca de seu proximo furo de reportagem, o jornalista Eddie Brock consegue uma entrevista exclusiva com Cletus Kasady, um assassino no corredor da morte, que descobre o segredo de Eddie e se torna o hospedeiro de Carnificina, um simbionte aterrorizante e ameacador.', 3.3, 3, 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/h5UzYZquMwO9FVn15R2eK2itmHu.jpg');
insert into TB_MOVIE(title, description, score, count, image) values ('Shang-Chi e a Lenda dos Dez Aneis', 'Shang-Chi precisa confrontar o passado que pensou ter deixado para tras. Ao mesmo tempo, ele e envolvido em uma teia de misterios da organizacao conhecida como Dez Aneis.', 0, 0, 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/ArrOBeio968bUuUOtEpKa1teIh4.jpg');
insert into TB_MOVIE(title, description, score, count, image) values ('Matrix Resurrections', 'Em um mundo de duas realidades — a vida cotidiana e o que esta por tras dela —, Thomas Anderson tera que escolher seguir o coelho branco mais uma vez. A escolha, embora seja uma ilusao, ainda e a unica maneira de entrar ou sair da Matrix, que e mais forte, mais segura e mais perigosa do que nunca.', 0, 0, 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/9DT4WVqZqBEI9Kub18gZ3m1D89m.jpg');
insert into TB_MOVIE(title, description, score, count, image) values ('Uncharted: Fora do Mapa', 'Nathan Drake e seu parceiro canastrao Victor "Sully" Sullivan embarcam em uma perigosa busca para encontrar o maior tesouro jamais encontrado. Enquanto isso, eles tambem rastreiam pistas que podem levar ao irmao perdido de Nathan.', 0, 0, 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/soD18uucENplI81kUErvMzdb5Lm.jpg');
insert into TB_MOVIE(title, description, score, count, image) values ('Batman', '????????????? Batman (2022) ?????????????', 0, 0, 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/wd7b4Nv9QBHDTIjc2m7sr0IUMoh.jpg');
insert into TB_MOVIE(title, description, score, count, image) values ('Sonic 2: O Filme', 'Depois de se estabelecer em Green Hills, Sonic esta pronto para mais liberdade e deixar sua marca como um heroi, e Tom e Maddie concordam em deixa-lo em casa enquanto vao de ferias. Mas, assim que eles se foram, Dr. Robotnik volta, desta vez com um novo parceiro.', 0, 0, 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/f4SvCKIUrC2cDR7Xo4k1kaGAqQ2.jpg');
insert into TB_MOVIE(title, description, score, count, image) values ('Homem-Aranha: Sem Volta Para Casa', 'Peter Parker e desmascarado e nao consegue mais separar sua vida normal dos grandes riscos de ser um super-heroi. Quando ele pede ajuda ao Doutor Estranho, os riscos se tornam ainda mais perigosos, e o forcam a descobrir o que realmente significa ser o Homem-Aranha.', 0, 0, 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/fVzXp3NwovUlLe7fvoRynCmBPNc.jpg');
insert into TB_MOVIE(title, description, score, count, image) values ('365 Dias: Hoje', 'Em 365 Dias: Hoje, apos os acontecimentos de 365 Dias, Laura Biel (Anna-Maria Sieklucka) se casa com Don Massimo Torricelli (Michele Morrone), o chefe da mafia siciliana que a sequestrou. Sua vida parece um conto de fadas: ela tem um marido amoroso, uma casa linda e um bebê a caminho. Mas...', 0, 0, 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/67vb4sQxJ06o4LvgoxB8Fj6mGqk.jpg');
insert into TB_MOVIE(title, description, score, count, image) values ('Ambulância: Um Dia de Crime', 'O condecorado veterano Will Sharp, desesperado por dinheiro para cobrir as despesas medicas de sua esposa, pede ajuda de uma pessoa que ele sabe que nao deveria - seu irmao adotivo Danny. Um criminoso carismatico, Danny oferece-lhe uma pontuacao: o maior assalto a banco na historia', 0, 0, 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/k62v5oVhQ0e1sJWJ9nFpiTfcNoD.jpg');
insert into TB_MOVIE(title, description, score, count, image) values ('Red: Crescer e Uma Fera', 'Mei, de treze anos, esta experimentando a estranheza de ser uma adolescente com uma reviravolta – quando ela fica muito animada, ela se transforma em um panda vermelho gigante.', 0, 0, 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/725WE0Qb1BbUF7aGvjiQqzzffpg.jpg');
insert into TB_MOVIE(title, description, score, count, image) values ('Virus-32', 'A virus is unleashed and a chilling massacre runs through the streets of Montevideo.', 0, 0, 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/wZiF79hbhLK1U2Pj9bF67NAKXQR.jpg');
insert into TB_MOVIE(title, description, score, count, image) values ('The Outfit', 'Leonard, um alfaiate inglês costumava fazer ternos na mundialmente famosa Savile Row de Londres. Mas depois de uma tragedia pessoal, ele acabou em Chicago, operando uma pequena alfaiataria em uma parte difícil da cidade', 0, 0, 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/lZa5EB6PVJBT5mxhgZS5ftqdAm6.jpg');
insert into TB_MOVIE(title, description, score, count, image) values ('Doutor Estranho no Multiverso da Loucura', 'Doutor Estranho, com a ajuda de aliados místicos antigos e novos, atravessa as perigosas realidades alternativas e alucinantes do Multiverso para enfrentar um novo adversario misterioso.', 0, 0, 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/hq2igFqb31fDqGotz8ZuUfwKgn8.jpg');

insert into TB_SCORE(user_id, movie_id, value) values (1, 1, 5.0);
insert into TB_SCORE(user_id, movie_id, value) values (1, 2, 4.0);
insert into TB_SCORE(user_id, movie_id, value) values (2, 1, 3.0);
insert into TB_SCORE(user_id, movie_id, value) values (2, 2, 3.0);
insert into TB_SCORE(user_id, movie_id, value) values (2, 3, 4.0);